apiVersion: v1
kind: ServiceAccount
metadata:
  name: dind-volume-cleanup
  labels:
    app: dind-volume-cleanup
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: dind-volume-cleanup
  labels:
    app: dind-volume-cleanup
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [list, get, patch]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dind-volume-cleanup
  labels:
    app: dind-volume-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dind-volume-cleanup
subjects:
  - kind: ServiceAccount
    name: dind-volume-cleanup
    namespace: monitoring
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dind-volume-cleanup
  labels:
    app: dind-volume-cleanup
spec:
  schedule: "0,10,20,30,40,50 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dind-volume-cleanup
          restartPolicy: Never
          containers:
            - name: dind-volume-cleanup
              image: codefresh/dind-volume-cleanup
              resources:
                requests:
                  cpu: '0.1'
                  memory: 96Mi
                limits:
                  cpu: '0.5'
                  memory: 128Mi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dind-volume-cleanup-m
  labels:
    app: dind-volume-cleanup
spec:
  schedule: "5,15,25,35,45,55 * * * 2-5"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dind-volume-cleanup
          restartPolicy: Never
          containers:
            - name: dind-volume-cleanup-m
              image: codefresh/dind-volume-cleanup
              args: [-m]
              resources:
                requests:
                  cpu: '0.1'
                  memory: 96Mi
                limits:
                  cpu: '0.5'
                  memory: 128Mi
