apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dind-volume-cleanup-ebs
  labels:
    app: dind-volume-cleanup
spec:
  schedule: "0,10,20,30,40,50 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dind-volume-cleanup
          restartPolicy: Never
          containers:
            - name: dind-volume-cleanup-ebs
              image: codefresh/dind-volume-cleanup
              env:
                - name: PROVISIONED_BY
                  value: codefresh.io/dind-volume-provisioner-ebs
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dind-volume-cleanup-m-ebs
  labels:
    app: dind-volume-cleanup
spec:
  schedule: "5,15,25,35,45,55 * * * 2-5"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dind-volume-cleanup
          restartPolicy: Never
          containers:
            - name: dind-volume-cleanup-m-ebs
              image: codefresh/dind-volume-cleanup
              args: [-m]
              env:
                - name: PROVISIONED_BY
                  value: codefresh.io/dind-volume-provisioner-ebs
