repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: cprom
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 34.6.0
    values:
      - templates/values.yaml.gotmpl
  - name: cf-monitoring
    namespace: monitoring
    chart: ./charts/cf-monitoring
    values:
      - templates/values.yaml.gotmpl

environments:
  default:
    values:
      - defaults.yaml.gotmpl
  local:
    values:
      - defaults.yaml.gotmpl
      - values.yaml
  dev:
    values:
      - defaults.yaml.gotmpl
    secrets:
      - ../codefresh.yaml
      - ../dev.yaml
  prod:
    values:
      - defaults.yaml.gotmpl
      - ../16.yaml
    secrets:
      - ../codefresh.yaml
      - ../prod.yaml
  prod32:
    values:
      - defaults.yaml.gotmpl
      - ../32.yaml
    secrets:
      - ../codefresh.yaml
      - ../prod.yaml
  prod8:
    values:
      - defaults.yaml.gotmpl
    secrets:
      - ../codefresh.yaml
      - ../prod.yaml
# ops-working-hours VictorOps channel
  prod-wh:
    values:
      - defaults.yaml.gotmpl
      - ../16.yaml
    secrets:
      - ../codefresh.yaml
      - ../prod-working-hours.yaml
