apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-exporter
  labels:
    app: event-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-exporter
  labels:
    app: event-exporter
rules:
  - apiGroups: [""]
    resources: [events]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter
  labels:
    app: event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-exporter
subjects:
- kind: ServiceAccount
  name: event-exporter
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: event-exporter
  template:
    metadata:
      labels:
        app: event-exporter
      annotations:
        prometheus_io_port: '9102'
        prometheus_io_scrape: 'true'
    spec:
      serviceAccountName: event-exporter
      containers:
        - name: event-exporter
          image: codefresh/k8s-event-exporter
          imagePullPolicy: Always
          args: [--running-in-cluster=true]
          resources:
            requests:
              cpu: '0.05'
              memory: 96Mi
            limits:
              cpu: '0.1'
              memory: 128Mi
