apiVersion: v1
kind: ServiceAccount
metadata:
  name: dind-monitor
  labels:
    app: dind-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dind-monitor
  labels:
    app: dind-monitor
rules:
  - apiGroups: [""]
    resources: [pods, persistentvolumes, persistentvolumeclaims]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dind-monitor
  labels:
    app: dind-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dind-monitor
subjects:
  - kind: ServiceAccount
    name: dind-monitor
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind-monitor
  labels:
    app: dind-monitor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dind-monitor
  template:
    metadata:
      labels:
        app: dind-monitor
      annotations:
        prometheus_io_port: '9100'
        prometheus_io_scrape: 'true'
    spec:
      serviceAccountName: dind-monitor
      tolerations:
        - key: codefresh/dind
          operator: Exists
          effect: NoSchedule
      containers:
        - image: codefresh/dind-volume-utils:v15
          name: dind-monitor
          imagePullPolicy: Always
          command: [/bin/dind-monitor]
          resources:
            requests:
              cpu: '1'
              memory: 400Mi
            limits:
              cpu: '2'
              memory: 600Mi
