{
 "title": "Codefresh / Build Metrics",
 "templating": {
  "list": [
   { "name": "dind_pod_name", "query": "label_values(pod_name)" }
  ]
 },
 "panels": [
  {
   "title": "Volume usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(docker_volume_kb_total{dind_pod_name=~\".*$dind_pod_name.*\"} - docker_volume_kb_available{dind_pod_name=~\".*$dind_pod_name.*\"})/1024^2",
     "legendFormat": "Volume usage (GB)"
    },
    {
     "expr": "docker_volume_kb_total{dind_pod_name=~\".*$dind_pod_name.*\"}/1024^2",
     "legendFormat": "Volume Size"
    }
   ]
  },
  {
   "title": "Dind Container CPU usage",
   "type": "graph",
   "description": "Shows CPU usage in CPU units",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".*dind_.*$dind_pod_name.*\"}[120s]))",
     "legendFormat": "CPUs Total (units)"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".*dind_.*$dind_pod_name.*\"}[120s])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Dind Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".*dind_.*$dind_pod_name.*\"} / 1000000000",
     "legendFormat": "Memory usage (GB)"
    },
    {
     "expr": "container_spec_memory_limit_bytes{name=~\".*dind_.*$dind_pod_name.*\"} / 1000000000",
     "legendFormat": "Memory limit (GB)"
    }
   ]
  },
  {
   "title": "Dind Container Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~\".*$dind_pod_name.*\"}[100s])) * 8 / 1000000",
     "legendFormat": "Network Receive Mbit/s"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~\".*$dind_pod_name.*\"}[100s])) * 8 / 1000000",
     "legendFormat": "Network Transmit Mbit/s"
    }
   ]
  }
 ]
}