{
 "title": "Codefresh / Cluster Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "throttle_threshold",
    "label": "CPU throttle threshold",
    "query": "10, 20, 30, 40, 50, 60, 70, 80, 90"
   },
   { "name": "namespace", "query": "workflow" }
  ]
 },
 "panels": [
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 *\nsum(increase(container_cpu_cfs_throttled_periods_total{container!=\"\", namespace=\"$namespace\"}[$__interval]))\nby (container, pod, namespace)\n/ sum(increase(container_cpu_cfs_periods_total{}[$__interval]))\nby (container, pod, namespace) > $throttle_threshold",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Overcommit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (kube_pod_container_resource_limits_cpu_cores)) / on(node) kube_node_status_allocatable_cpu_cores > 1\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Overcommit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (kube_pod_container_resource_limits_memory_bytes)) / on(node) kube_node_status_allocatable_memory_bytes > 1",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Evicted Pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Evicted\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=\"Pending\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOM Killed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated_reason{reason=\"OOMKilled\",namespace=\"$namespace\"} == 1",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}