{
 "title": "Codefresh / Dind and Engine resources",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "build_id",
    "label": "Build ID",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"workflow\"}, pod)"
   },
   { "name": "interval", "query": "4h" }
  ]
 },
 "panels": [
  {
   "title": "Build Steps",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(workflow_step_duration{phase_name=~\"(presteps|poststeps|user)\", kubernetes_pod_name=\"engine-$build_id\", step_name != \"\"}[20s]) != 0",
     "legendFormat": "{{phase_name}}: {{step_name}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"workflow\", pod=~\"(dind|engine)-$build_id\", container!=\"POD\", cluster=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"workflow\", pod=~\"(dind|engine)-$build_id\", container!=\"POD\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}} (RSS)"
    },
    {
     "expr": "sum(container_memory_cache{cluster=\"$cluster\", namespace=\"workflow\", pod=~\"(dind|engine)-$build_id\", container!=\"POD\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}} (Cache)"
    },
    {
     "expr": "sum(container_memory_swap{cluster=\"$cluster\", namespace=\"workflow\", pod=~\"(dind|engine)-$build_id\", container!=\"POD\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}} (Swap)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"workflow\", pod=~\"(dind|engine)-$build_id\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"workflow\", pod=~\"(dind|engine)-$build_id\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"workflow\", pod=~\"(dind|engine)-$build_id\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"workflow\", pod=~\"(dind|engine)-$build_id\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}