{
 "title": "Codefresh / Pipeline metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pipeline_id",
    "label": "Pipeline ID",
    "query": "label_values(dind_pod_status,  label_io_codefresh_pipeline_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Consumption(AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without (pod) (\n  avg by (pod) (\n    rate(container_cpu_usage_seconds_total{pod=~\"^dind-.*\",container!=\"POD\"}[40s])\n  )\n  * on(pod) group_left( label_io_codefresh_pipeline_id) \n  dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Consumption(AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by ( label_io_codefresh_pipeline_id) (\n  avg by (pod,  label_io_codefresh_pipeline_id) (\n    container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}\n    * on(pod) group_left( label_io_codefresh_pipeline_id) \n    dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Volume Consumption(AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (io_codefresh_pipeline_id) (\n\t(docker_volume_kb_total{io_codefresh_pipeline_id=\"$pipeline_id\"} - docker_volume_kb_available{io_codefresh_pipeline_id=\"$pipeline_id\"})\n)"
    }
   ]
  },
  {
   "title": "CPU Consumption(MAX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max without (pod) (\n  avg by (pod) (\n    rate(container_cpu_usage_seconds_total{pod=~\"^dind-.*\",container!=\"POD\"}[40s])\n  )\n  * on(pod) group_left( label_io_codefresh_pipeline_id) \n  dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Consumption(MAX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by ( label_io_codefresh_pipeline_id) (\n  max by (pod,  label_io_codefresh_pipeline_id) (\n    container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}\n    * on(pod) group_left( label_io_codefresh_pipeline_id) \n    dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Volume Consumption(MAX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (io_codefresh_pipeline_id) (\n\t(docker_volume_kb_total{io_codefresh_pipeline_id=\"$pipeline_id\"} - docker_volume_kb_available{io_codefresh_pipeline_id=\"$pipeline_id\"})\n)"
    }
   ]
  },
  {
   "title": "CPU Percentage Usage (AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max ( \n  (\n    (max by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"^dind-[0-9].*\",container!=\"POD\"}[40s]))) /\n    (max by (pod) (kube_pod_container_resource_limits_cpu_cores{pod=~\"^dind-[0-9].*\"}))\n  )\n  * on(pod) group_left( label_io_codefresh_pipeline_id) \n  dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Percentage Usage (AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max (\n  ( \n    ( max by (pod) (container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}) ) / \n    ( max by (pod) (kube_pod_container_resource_limits_memory_bytes{pod=~\"^dind-[0-9].*\"})  )\n  )\n  * on(pod) group_left( label_io_codefresh_pipeline_id) \n  dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n)"
    }
   ]
  },
  {
   "title": "CPU Percentage Usage (MAX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max ( \n  (\n    (max by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"^dind-[0-9].*\",container!=\"POD\"}[40s]))) /\n    (max by (pod) (kube_pod_container_resource_limits_cpu_cores{pod=~\"^dind-[0-9].*\"}))\n  )\n  * on(pod) group_left( label_io_codefresh_pipeline_id) \n  dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n)"
    }
   ]
  },
  {
   "title": "Memory Percentage Usage (AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max (\n  ( \n    ( max by (pod) (container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}) ) / \n    ( max by (pod) (kube_pod_container_resource_limits_memory_bytes{pod=~\"^dind-[0-9].*\"})  )\n  )\n  * on(pod) group_left( label_io_codefresh_pipeline_id) \n  dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n)"
    }
   ]
  },
  {
   "title": "Pipeline CPU Consumption",
   "type": "graph",
   "description": "Consumption of CPU for the specified pipeline.\nBroken down per build ID and aggregated for the whole pipeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (pod) (\n  avg by (pod) (\n    rate(container_cpu_usage_seconds_total{pod=~\"^dind-.*\",container!=\"POD\"}[40s])\n  )\n  * on(pod) group_left( label_io_codefresh_pipeline_id) \n  dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n)",
     "legendFormat": "Pipeline(avg)={{ label_io_codefresh_pipeline_id}}"
    },
    {
     "expr": "avg by (pod) (\n  rate(container_cpu_usage_seconds_total{pod=~\"^dind-.*\",container!=\"POD\"}[40s])\n)\n* on(pod) group_left( label_io_codefresh_pipeline_id) \ndind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}",
     "legendFormat": "Build={{pod}}"
    }
   ]
  },
  {
   "title": "Dind Container Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by ( label_io_codefresh_pipeline_id) (\n  avg by (pod,  label_io_codefresh_pipeline_id) (\n    container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}\n    * on(pod) group_left( label_io_codefresh_pipeline_id) \n    dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n  )\n)",
     "legendFormat": "Pipeline(avg)={{ label_io_codefresh_pipeline_id}}"
    },
    {
     "expr": "\n  avg by (pod,  label_io_codefresh_pipeline_id) (\n    container_memory_usage_bytes{pod=~\"^dind-[0-9].*\", container_name!=\"POD\"}\n    * on(pod) group_left( label_io_codefresh_pipeline_id) \n    dind_pod_status{ label_io_codefresh_pipeline_id=\"$pipeline_id\", label_app=\"dind\", phase=\"Running\"}\n  )\n",
     "legendFormat": "Build={{pod}}"
    }
   ]
  },
  {
   "title": "Pipeline Volume Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (io_codefresh_pipeline_id) (\n\t(docker_volume_kb_total{io_codefresh_pipeline_id=\"$pipeline_id\"} - docker_volume_kb_available{io_codefresh_pipeline_id=\"$pipeline_id\"})\n)",
     "legendFormat": "Pipeline(avg)={{io_codefresh_pipeline_id}}"
    },
    {
     "expr": "(docker_volume_kb_total{io_codefresh_pipeline_id=\"$pipeline_id\"} - docker_volume_kb_available{io_codefresh_pipeline_id=\"$pipeline_id\"})",
     "legendFormat": "Build={{dind_pod_name}}"
    }
   ]
  },
  {
   "title": "Volume usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(docker_volume_kb_total{dind_pod_name=\"dind-$build_id\"} - docker_volume_kb_available{dind_pod_name=\"dind-$build_id\"})/1024^2",
     "legendFormat": "Volume usage (GB)"
    },
    {
     "expr": "docker_volume_kb_total{dind_pod_name=\"dind-$build_id\"}/1024^2",
     "legendFormat": "Volume Size"
    }
   ]
  },
  {
   "title": "Dind Container CPU usage",
   "type": "graph",
   "description": "Shows CPU usage in CPU units",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=\"dind-$build_id\",container!=\"POD\"}[40s])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Dind Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=\"dind-$build_id\"} / 1000000000",
     "legendFormat": "Memory usage (GB)"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=\"dind-$build_id\"} / 1000000000",
     "legendFormat": "Memory limit (GB)"
    }
   ]
  },
  {
   "title": "Dind Container Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"dind-$build_id\"}[100s])) * 8 / 1000000",
     "legendFormat": "Network Receive Mbit/s"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"dind-$build_id\"}[100s])) * 8 / 1000000",
     "legendFormat": "Network Transmit Mbit/s"
    }
   ]
  },
  {
   "title": "Dind Container Network Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"dind-$build_id\"}[100s])) * 8 / 1000000",
     "legendFormat": "Network Receive Mbit/s"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=\"dind-$build_id\"}[100s])) * 8 / 1000000",
     "legendFormat": "Network Transmit Mbit/s"
    }
   ]
  }
 ]
}