{
 "title": "Codefresh / Workflow init phase duration (per build)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "build_id",
    "label": "Build ID",
    "query": "label_values(kube_pod_info, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "K8s Events Duration Diagram",
   "type": "graph",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "kubernetes_events_timestamp{event_name=\"dind-$build_id\", event_reason=\"ProvisioningSucceeded\"} - on(event_name) kubernetes_events_timestamp{event_name=\"dind-$build_id\", event_reason=\"ExternalProvisioning\"} + scalar(kubernetes_events_duration{event_name=\"dind-$build_id\", event_reason=\"FailedScheduling\", event_message=~\".*has unbound.*\"})",
     "legendFormat": "{{Volume Provisioning}} (dind)"
    },
    {
     "expr": "kubernetes_events_timestamp{event_name=\"dind-$build_id\", event_reason=\"Pulled\"} - on(event_name) label_replace(kubernetes_events_timestamp{event_reason=\"ProvisioningSucceeded\"}, \"event_name\", \"$2\", \"event_name\", \"(pvc-)(dind-$build_id.*)\")",
     "legendFormat": "{{Volume Attach & Mount}} (dind)"
    },
    {
     "expr": "kubernetes_events_timestamp{event_name=\"dind-$build_id\", event_reason=\"Created\"} - on(event_name) kubernetes_events_timestamp{event_name=\"dind-$build_id\", event_reason=\"Pulled\"}",
     "legendFormat": "{{Pod Creation}} (dind)"
    },
    {
     "expr": "kubernetes_events_duration{event_name=\"dind-$build_id\", event_reason!~\"Killing|FailedScheduling|ExternalProvisioning\", event_type!=\"Warning\"} != 0",
     "legendFormat": "{{event_reason}} (dind)"
    },
    {
     "expr": "kubernetes_events_duration{event_name=\"dind-$build_id\", event_reason=\"FailedScheduling\", event_message!~\"pod has unbound immediate PersistentVolumeClaims.*\"}",
     "legendFormat": "{{Pod scheduling}}"
    }
   ]
  },
  {
   "title": "Init Steps Duration Diagram",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "workflow_step_duration{phase_name=\"presteps\", kubernetes_pod_name=\"engine-$build_id\"} !=0 ",
     "legendFormat": "{{step_name}}"
    }
   ]
  },
  {
   "title": "K8s Events on Timeline",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dateTimeAsUS" }
   ],
   "targets": [
    {
     "expr": "kubernetes_events_timestamp{event_name=\"dind-$build_id\", event_reason!=\"Killing\"} * 1000",
     "legendFormat": "{{event_reason}}(dind){{event_message}}"
    }
   ]
  }
 ]
}